app/src/generated/graphql.ts
app/src/pages/manage/competencies/[id]/create.vue
app/src/pages/manage/competencies/[id]/edit.vue
app/src/pages/manage/competencies/[id]/index.vue
app/themes/base.ts

12 delete competency

---

api/package.json
api/src/plugins/graphql.ts
yarn.lock

GraphiQL is exposed at http://localhost:3030/graphql

➖ remove altair graphql client

---

api/prisma/migrations/20220420121712_/migration.sql
api/prisma/schema.prisma
api/src/domain/competency.ts
api/src/generated/schema.graphql
api/src/schema/types/competency.ts
app/src/generated/graphql.ts

Ref: #11
Co-Authored-By: Nikolay Neykov <nikolai.neikov@gmail.com>

✨ implement competency sort (api)

---

api/src/generated/schema.graphql
app/src/components/forms/create-competency-form.vue
app/src/components/forms/create-competency-framework.vue
app/src/components/forms/create-root-competency.vue
app/src/generated/graphql.ts
app/src/pages/manage/frameworks/[frameworkId]/[competencyId]/edit.vue
app/src/spec/mocks/handlers.ts

After merge of #149 many types had to be reset.

Bugfix payloads

---

api/prisma/schema.prisma
api/src/domain/competency.ts
api/src/generated/schema.graphql
api/src/schema/types/competency.ts
api/test/fixtures.ts
app/src/generated/graphql.ts

And remove old `createCompetency` code.
Ref: #109

✨ set competency framework nullability correctly

---

app/src/components/auth/unauthorized.vue
app/src/generated/components.d.ts
app/src/locales/global.en.yaml
app/src/locales/global.nl.yaml
app/src/pages/manage/frameworks/[frameworkId]/[competencyId]/create-competency.vue
app/src/pages/manage/frameworks/[frameworkId]/[competencyId]/edit.spec.ts
app/src/pages/manage/frameworks/[frameworkId]/[competencyId]/edit.vue
app/src/pages/manage/frameworks/[frameworkId]/create-competency.vue
app/src/pages/manage/frameworks/create-framework.vue
app/src/router.ts

For now I just replaced the route guards with an "unauthorized" component render. These guards were only placed on forms. This means anyone can still reorder and delete competencies. I assume we will deal with those once roles are available.

Autorization component 148

---

api/src/codegen/schema.graphql
api/src/domain/competency.ts
api/src/schema/types/competency.ts
api/test/competency-mutations.spec.ts
api/test/competency-queries.spec.ts
app/src/codegen/graphql.ts
app/src/pages/manage/frameworks/[frameworkId]/[competencyId]/create-competency.vue
app/src/pages/manage/frameworks/[frameworkId]/[competencyId]/edit.vue
app/src/pages/manage/frameworks/[frameworkId]/[competencyId]/index.vue
app/src/pages/manage/frameworks/[frameworkId]/create-competency.vue
app/src/pages/manage/frameworks/[frameworkId]/index.vue
app/src/spec/mocks/handlers.ts

The error is added to all `competency` operations.

🥅  add `AppNotFound` error to all `ID` operations

---

app/src/components/title/ui-subtitle.vue
app/src/components/title/ui-title.vue
app/src/pages/demo/forms.vue
app/src/pages/demo/ui.vue
app/src/pages/manage/frameworks/[frameworkId]/[competencyId]/create-competency.vue
app/src/pages/manage/frameworks/[frameworkId]/[competencyId]/index.vue
app/src/pages/manage/frameworks/[frameworkId]/create-competency.vue
app/src/pages/manage/frameworks/[frameworkId]/index.vue
app/src/pages/manage/frameworks/create-framework.vue
app/src/pages/manage/frameworks/index.vue
app/src/vite-types/components.d.ts

💄 design ui-title / ui-subtitle

---

app/src/components/button/ui-icon-button.vue

💄 design icon button

---

api/package.json
api/rollup.config.mjs
api/src/api.spec.ts
api/src/api/api.ts
api/src/api/auth.ts
api/src/api/graphql.ts
api/src/api/health.ts
api/src/app.ts
api/src/domain/competency.ts
api/src/domain/education.ts
api/src/domain/helpers/handle-service-error.ts
api/src/domain/helpers/index.ts
api/src/domain/helpers/language.ts
api/src/domain/helpers/validators.ts
api/src/domain/user.ts
api/src/plugins/prisma.ts
api/src/prisma.ts
api/src/schema/context.ts
api/src/schema/types/accountable.ts
api/src/schema/types/competency.ts
api/src/schema/types/current-user.ts
api/src/schema/types/education.ts
api/src/schema/types/errors.ts
api/src/schema/types/person.ts
api/src/server.ts
api/tsconfig.json
api/vitest.config.ts
yarn.lock

Ref: 06ce238d865bb778d4cbca538099abea87d361f4
This wasn't possible with our previous build but it is now.

🧑‍💻 allow `~/` source imports

---

app/src/pages/manage/frameworks/[frameworkId]/[competencyId]/create-competency.vue
app/src/pages/manage/frameworks/[frameworkId]/[competencyId]/edit.vue
app/src/pages/manage/frameworks/[frameworkId]/create-competency.vue
app/src/pages/manage/frameworks/create-framework.vue

`isLoggedIn` is only for authentication, not for authorization.

♻️ use authorization checks for competencies

---

app/src/components/input/ui-input-text.vue
app/src/formkit/plugin.ts
app/src/pages/demo/forms.vue
app/src/pages/demo/ui.vue
app/src/vite-types/components.d.ts

💄 create `ui-input-text` component

---

app/src/components/navigation/ui-main-nav-link.vue
app/src/components/navigation/ui-main-nav.vue
app/src/layout.vue
app/src/vite-types/components.d.ts

💄  create ui components for the side navigation

---

app/src/components/input/fk-input-text.vue
app/src/formkit/plugin.ts
app/src/pages/demo/ui.vue
app/src/vite-types/components.d.ts

🐛  update the `UiInputText` component `FormKit` integration

---

app/src/components/input/fk-checkbox.vue
app/src/components/input/fk-radio.vue
app/src/components/select/fk-select.vue

💄  pass the `id` from the `FormKit` context to the UI components

---

app/src/domain/competency-management/components/competency-list.vue
app/src/pages/manage/frameworks/index.vue
app/src/ui/list/ui-ordered-list-item.vue
app/src/ui/list/ui-ordered-list.vue
app/src/vite-types/components.d.ts

💄 create an ordered list ui component

---

app/src/ui/list/ui-ordered-list-item.vue
app/src/ui/list/ui-ordered-list.vue

💄  Style the ordered list UI component

---

app/src/pages/demo/ui.vue
app/src/ui/input/fk-radio.vue
app/src/ui/input/ui-checkbox.vue
app/src/ui/input/ui-radio-group.vue
app/src/ui/input/ui-radio.vue

Het werkt, maar ik ben niet zeker of het volgens de regels geschreven is. Graag feedback!
Ref: #214, #215

💄 add disabled states for checkbox and radio

---

app/src/domain/global/components/layout/main-layout.vue
app/src/domain/global/components/layout/user-menu.vue
app/src/ui/breadcrumb/ui-breadcrumb-link.vue
app/src/ui/breadcrumb/ui-breadcrumb.vue
app/src/ui/list/ui-ordered-list-item.vue
app/src/ui/main-nav/ui-main-nav-header.vue
app/src/ui/main-nav/ui-main-nav-link.vue

- Uniform paddings / focus outline on interactive elements
- Apply explicit text size everywhere
- Simplify breadcrumb implementation

💄 design tweaks

---

api/src/api/ability.ts
api/src/api/auth.ts
api/src/codegen/schema.graphql
api/src/schema/types/auth.ts
api/src/schema/types/index.ts
app/src/auth.ts
app/src/codegen/graphql.ts
app/src/main.ts

✨ give anonymous users explicit abilities

---

app/src/domain/competency-management/components/competency-list.vue
app/src/domain/competency-management/components/framework-list.vue
app/src/ui/breadcrumb/ui-breadcrumb-item.vue
app/src/ui/list/ui-ordered-list-item.vue

These are only the design issues: #295 & #296, I would like to PR the other issues from #298 separately.
Included small fix for https://github.com/OpenSkool/OpenSkool/commit/61e9a509006c6e014a7f539ea55ef75c6719e686

Ac rework 298

---

app/src/domain/competency-management/components/framework-list.vue
app/src/domain/competency-management/components/root-competencies-page.vue

@Moeriki, kijk je even na of Frameworks api meer error-handling moet krijgen?

Replace use result 300

---

api/prisma/migrations/20220607175309_/migration.sql
api/prisma/schema.prisma
api/prisma/seed.ts
api/src/codegen/schema.graphql
api/src/domain/competency.ts
api/src/schema/types/competency.ts
api/test/fixtures.ts
app/src/codegen/graphql.ts
app/src/domain/competency-management/components/competency-create-page.vue
app/src/domain/competency-management/components/competency-edit-page.vue
app/src/domain/competency-management/components/competency-list-page.vue
app/src/domain/competency-management/components/root-competency-create.vue
app/src/spec/mocks/handlers.ts

If and only if the context is clearly indicating competencies.

🚚 rename competencyFramework to framework

---

api/src/api/api.ts
api/src/codegen/schema.graphql
api/src/schema/types/auth.ts
app/src/auth.ts
app/src/codegen/graphql.ts

✨  log out the user when not active

---

api/prisma/migrations/20220615125822_/migration.sql
api/prisma/schema.prisma
api/prisma/seed.ts
api/src/codegen/schema.graphql
api/src/domain/course.ts
api/src/domain/internship.ts
api/src/schema/types/internship.ts
api/test/internship-queries.spec.ts
app/src/codegen/graphql.ts
app/src/domain/global/components/main-menu/main-menu.vue

Use an `implicit many-to-many` relation between the `Course` and the `Internship` models

🗃️ change the relation of `internship/course`

---

api/prisma/fixtures/index.ts
api/prisma/migrations/20220616152824_/migration.sql
api/prisma/migrations/20220617145337_/migration.sql
api/prisma/migrations/20220620113525_/migration.sql
api/prisma/schema.prisma
api/prisma/seed.ts
api/src/codegen/schema.graphql
api/src/domain/index.ts
api/src/domain/internship.ts
api/src/domain/organisation.ts
api/src/domain/types.d.ts
api/src/schema/types/internship.ts
api/src/schema/types/organisation.ts
api/test/internship-queries.spec.ts
app/src/codegen/graphql.ts
app/src/pages/my-internships/[internshipInstanceId]/index.vue

Internship position 262
